export const appImages = {
  Splash: require('../images/Splash.png'),
  appIntroOne: require('../images/FeatureA.png'),
  appIntroTwo: require('../images/FeatureB.png'),
  appIntroThree: require('../images/FeatureC.png'),
  appIntroFour: require('../images/FeatureD.png'),
  continueAs: require('../images/ContinueAs.png'),
  privacyBanner: require('../images/privacyBanner.png'),
  termsBanner: require('../images/termsBanner.png'),
  yourLocation: require('../images/yourLocation.png'),
  noNotification: require('../images/noNotification.png'),
  userPlaceholder: require('../images/placeholder.jpg'),
  locationView: require('../images/locationView.jpeg'),
  sittingView: require('../images/sittingArea.jpeg'),
};
